name: tiffany wan
favicon: null
layout_spectrum: 0.6082407247740775
typography_spectrum: 0.49252344691194594
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.3605145555920899
  lightness: 0.025340812280774117
  saturation: 0.7916886808816344
  rhythmicContrast: 0.12378636724315584
purpose: []
